### ISSUE TITLE
Serve a sub-directory of the repository

### ISSUE THREAD

**Issue by MatthieuBizien** [Priv-Page/privpage#5]
I'm experimenting with privpage, it helps a lot serving private documentation to our team easily.

A limitation I have is that documentations are often generated in a specific sub-directory (eg. `doc/`). It would be great to enable serving from that sub-directory.

It could be implemented simply with a .privpage file at the root, that could configure where to serve.

**Comment by j8r** [comment]
That can be a good idea, but a good point of this project is to be zero-conf, and it complexifies the logic of the service.

It means, for a given`test` branch (I suppose your branch is not prefixed by `privpage`):
- try to get `privpage-test`
- if not existing, try the branch `test`, which must have a `.privpage` file
- get and parse this file, then accordingly serve the requested URL resource.

And that, for all requests 😕

**Comment by j8r** [comment]
Of course, I can add caching, but the main point is there will always have more API calls, in part caused by the service logic being more complex.

I understand your workflow is to generate docs in `/doc`. Now, GitHub actions being free, I'm pretty sure a satisfying workaround can be found: the CI can create/update a `privpage` branch with the content of `/doc`.

**Comment by j8r** [comment]
I suspect this issue to come back, being an available feature of GitHub.

I will post an example in the following days: the CI will take the content of `mybranch/docs`, and push it to a `privpage-mybranch` branch.

**Comment by MatthieuBizien** [comment]
> try to get privpage-test
> if not existing, try the branch test, which must have a .privpage file
> get and parse this file, then accordingly serve the requested URL resource.

That was not the workflow I had in mind. I was thinking of something simpler:
- Get privpage-test
- Look for a .privpage file. 
- If there is none, keep the current behaviour
- If there is one, use that file for choosing which directory of the branch privpage-test to serve

It keep the nice separation between privpage-* branchs and dev git branches, and don't add auto-generated doc to master/. I can add a CI in my master branch to:
- checkout the privpage branch.
- merge master.
- generate documentation in doc/.
- commit and push to the privpage branch.

**Comment by j8r** [comment]
Where does the `privpage-test` comes from at first? It is likely create specifically to serve docs. It works to checkout a given branch, generate docs, place it somewhere, create an orphaned branch, place the docs inside then push-force this.

**Comment by j8r** [comment]
Here is an example for a `Crystal` project, with `crystal docs` generating its docs in the `/docs` director (but you can add an `mv doc /docs` in your case):
```yml
name: Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: shards install
      - name: Build
        run: crystal docs -o /docs
      - name: Deploy
        run: |
          git config user.name CI
          git config user.email ""
          git checkout -f --orphan gh-pages
          git rm --cached -rfq .
          git clean -fxdq
          mv /docs/* .
          git add .
          git commit -qm "Update docs"
          git push -f --set-upstream origin gh-pages
```

**Comment by j8r** [comment]
Here is an example for a `Crystal` project, with `crystal docs` generating its docs in the `/docs` director (but you can add an `mv doc /docs` in your case):
```yml
name: Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: shards install
      - name: Build
        run: crystal docs -o /docs
      - name: Deploy
        run: |
          git config user.name CI
          git config user.email ""
          git checkout -f --orphan privpage-${GITHUB_REF##*/}
          git rm --cached -rfq .
          git clean -fxdq
          mv /docs/* .
          git add .
          git commit -qm "Update docs"
          git push -f --set-upstream origin privpage-${GITHUB_REF##*/}
```

**Comment by j8r** [comment]
Here is an example for a `Crystal` project, with `crystal docs` generating its docs in the `/docs` directory (but you can add an `mv doc /docs` in your case):
```yml
name: Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: shards install
      - name: Build
        run: crystal docs -o /docs
      - name: Deploy
        run: |
          git config user.name CI
          git config user.email ""
          git checkout -f --orphan privpage-${GITHUB_REF##*/}
          git rm --cached -rfq .
          git clean -fxdq
          mv /docs/* .
          git add .
          git commit -qm "Update docs"
          git push -f --set-upstream origin privpage-${GITHUB_REF##*/}
```

**Comment by j8r** [comment]
Here is an example for a `Crystal` project, with `crystal docs` generating its docs in the `/docs` directory (but you can add an `mv doc /docs` in your case):
```yml
name: Documentation

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: shards install
      - name: Build
        run: crystal docs -o /docs
      - name: Deploy
        run: |
          git config user.name CI
          git config user.email ""
          git checkout -f --orphan privpage-${GITHUB_REF##*/}
          git rm --cached -rfq .
          git clean -fxdq
          mv /docs/* .
          git add .
          git commit -qm "Update docs"
          git push -f --set-upstream origin privpage-${GITHUB_REF##*/}
```

**Comment by MatthieuBizien** [comment]
I was able to make it work thanks to your template. Adding it in the README of the repository would be very helpful.

Here is the Python template with pdoc, if it can get someone up-to-speed:

```
name: Documentation

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Documentation
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: install-pdoc
        run: pip install pdoc==0.3.2
      - name: install-dependencies
        run: pip install .
      - name: build-documentation
        run: PYTHONPATH="$(pwd)" pdoc --html mymodule --html-dir /tmp/docs
      - name: Deploy
        run: |
          git config user.name CI
          git config user.email ""
          git checkout -f --orphan privpage-${GITHUB_REF##*/}
          git rm --cached -rfq .
          git clean -fxdq
          mv /tmp/docs/mymodule/* .
          git add .
          git commit -qm "Update docs: $GITHUB_SHA"
          git push -f --set-upstream origin privpage-${GITHUB_REF##*/}
```

Thanks for your help! I leave that issue open as the feature is not added, but feel free to close it if you want as my problem is solved.
